Added: BookController, BookDto layer, BookMapper, findById method to …
pavlov-n/book-shop pull request #2
Opened 2023-10-20 08:43 UTC by pavlov-n

…bookRepository and bookService. Updated: pom.xml file(added dependencies for mapper).

2023-10-20 13:30 UTC, liliia-ponomarenko requested changes
Good job! Let’s  improve your solution ;)

2023-10-20 13:30 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/config/MapperConfig.java
> +)
it is better to specify @MapperConfig directly above the mapper class

2023-10-20 13:30 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/dto/BookDto.java
> +public class BookDto {
better use record

2023-10-20 13:30 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/dto/CreateBookRequestDto.java
> +public class CreateBookRequestDto {
the same

2023-10-20 13:30 UTC, liliia-ponomarenko commented on src/main/java/com/bookshop/service/impl/BookServiceImpl.java
> +        return bookMapper.toDto(book);
we can make use of Optional's map method here:

```
return repository.findById(id)
            .map(bookMapper::toDto)
            .orElseThrow(...);
```

2023-10-21 15:33 UTC, NazarSmith228 approved these changes
LGTM, but please pay attention to my remarks

2023-10-21 15:33 UTC, NazarSmith228 commented on src/main/java/com/bookshop/mapper/BookMapper.java
> +    Book toModel(CreateBookRequestDto requestDto);
`toBook` sounds better :)

2023-10-21 15:33 UTC, NazarSmith228 commented on src/main/java/com/bookshop/repository/impl/BookRepositoryImpl.java
> +        return sessionFactory.fromSession(s -> Optional.ofNullable(s.get(Book.class, id)));
you might also need to handle possible exception here

2023-10-23 07:25 UTC, merged