Added GlobalExceptionHandler and validation
pavlov-n/book-shop pull request #4
Opened 2023-10-24 06:13 UTC by pavlov-n

2023-10-24 14:08 UTC, Alexsandr-Yablunovskyi approved these changes
Good job!

2023-10-24 15:55 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-10-24 15:55 UTC, Elena-Bruyako commented on pom.xml
> +            <artifactId>hibernate-validator</artifactId>
it is better to use spring-boot-starter-validation

2023-10-24 15:55 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/controller/BookController.java
> +    public BookDto getBookById(@PathVariable @Positive Long id) {
@PathVariable @Positive Long id
In order to be able to perform such validation you need to annotate your controller class with Validated annotation

2023-10-24 15:55 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/dto/CreateBookRequestDto.java
>          String isbn,
It's better to validate isbn by using a pattern

2023-10-24 15:55 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/exception/CustomGlobalExceptionHandler.java
> +
remove empty line

2023-10-24 15:55 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/exception/CustomGlobalExceptionHandler.java
> +        body.put("timestamp", LocalDateTime.now());
do you really need time here?

2023-10-24 15:55 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/exception/CustomGlobalExceptionHandler.java
> +        body.put("status", HttpStatus.BAD_REQUEST);
there is no sense to store status in the response body - it is obvious from the response itself

2023-10-24 15:55 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/exception/CustomGlobalExceptionHandler.java
> +        return new ResponseEntity<>(body, HttpStatus.NOT_FOUND);
```suggestion
        return ResponseEntity
                .status(HttpStatus.NOT_FOUND)
                .body(exception.getMessage());
```

2023-10-27 12:38 UTC, NazarSmith228 approved these changes
LGTM! But please pay attention to my remarks

2023-10-27 12:38 UTC, NazarSmith228 commented on pom.xml
> +            <version>3.1.5</version>
no need to specify the version - it is taken from `spring-boot-starter-parent`

2023-10-27 12:38 UTC, NazarSmith228 commented on src/main/java/com/bookshop/dto/CreateBookRequestDto.java
> +        @Pattern(regexp = "^\\d{3}-\\d{10}$")
I assume that `@NotBlank` is redundant here, since blank string should not match the regex

double check that :)

2023-10-27 12:45 UTC, merged