added registration, authorization through jwt
pavlov-n/book-shop pull request #6
Opened 2023-11-06 09:37 UTC by pavlov-n

2023-11-06 09:42 UTC, pavlov-n commented
I added some viewed files in git, because i rebased some files in new packages. If you want, you can choose filter of viewed files.

2023-11-06 14:49 UTC, Parashchuk approved these changes
LGTM

2023-11-07 08:45 UTC, NazarSmith228 requested changes
Good job! Let's improve your solution

2023-11-07 08:45 UTC, NazarSmith228 commented on pom.xml
> +            <version>4.22.0</version>
you may skip the version - it is taken from `spring-boot-starter-parent`

2023-11-07 08:45 UTC, NazarSmith228 commented on pom.xml
> +        </dependency>
this is a plugin - pls remove from dependencies section

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/config/SecurityConfig.java
> +    ) throws Exception {
```suggestion
            AuthenticationConfiguration authenticationConfiguration) throws Exception {
```

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/controller/AuthenticationController.java
> +@Validated
you don't need this annotation here - there is no `@PathVariable` etc.

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/controller/AuthenticationController.java
> +
redundant blank lines

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/controller/BookController.java
> +    @PreAuthorize("hasAnyRole('ROLE_ADMIN', 'ROLE_USER')")
1. `hasRole` adds `ROLE_` prefix automatically - you may not specify it
2. doesn't ADMIN has all the priviliges USER has? if yes - then you can simplify to `hasRole("USER")`. if not - feel free to skip it

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/dto/user/UserRegistrationRequestDto.java
> +        String verifyPassword,
shouldn't you have `@FieldMatch` annotation for validating equality of these properties?

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/dto/user/UserLoginRequestDto.java
> +        String password) {}
```suggestion
        String password) {
}
```

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/dto/user/UserLoginResponseDto.java
> +public record UserLoginResponseDto(String token){}
```suggestion
public record UserLoginResponseDto(String token){
}
```

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/dto/user/UserRegistrationRequestDto.java
> +) {
```suggestion
        String shippingAddress) {
```

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/jwt/JwtAuthenticationFilter.java
> +    ) throws ServletException, IOException {
```suggestion
            FilterChain filterChain) throws ServletException, IOException {
```

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/jwt/JwtAuthenticationFilter.java
> +            return bearerToken.substring(7);
makes sense to declare a constant
```suggestion
        if (StringUtils.hasText(bearerToken) && bearerToken.startsWith(BEARER_TYPE)) {
            return bearerToken.substring(BEARER_TYPE.length());
```

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/model/RoleName.java
> +public enum RoleName {
this might be nested in `Role` class

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/model/User.java
> +    @ManyToMany
be careful with `@Data` since it will include roles when it may be inappropriate

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/security/AuthenticationService.java
> +        final Authentication authentication = authenticationManager.authenticate(
```suggestion
        Authentication authentication = authenticationManager.authenticate(
```

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/security/CustomUserDetailsService.java
> +                .orElseThrow(() -> new UsernameNotFoundException(
do you handle this exception in your controller advice?

2023-11-07 08:45 UTC, NazarSmith228 commented on src/main/java/com/bookshop/security/CustomUserDetailsService.java
> +    public UserDetails loadUserByUsername(String username) throws UsernameNotFoundException {
```suggestion
    public UserDetails loadUserByUsername(String username) {
```

2023-11-14 16:00 UTC, Elena-Bruyako requested changes
Good job! Let's improve your solution!

2023-11-14 16:00 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/dto/user/UserLoginRequestDto.java
> +
remove empty line

2023-11-14 16:00 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/dto/user/UserLoginRequestDto.java
> +        @NotNull @Email
Please check which regexp is used in `@Email` validation. Maybe it's better to add custom one

2023-11-14 16:00 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/model/User.java
> +    @ManyToMany
```
 @EqualsAndHashCode.Exclude
 @ToString.Exclude
```

2023-11-14 16:00 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/service/impl/UserServiceImpl.java
> +        if (userRepository.findByEmail(request.email()).isPresent()) {
it's better to use existsByEmail to avoid calling isPresent here

2023-11-14 16:00 UTC, Elena-Bruyako commented on src/main/java/com/bookshop/validation/FieldMatcherValidator.java
> +public class FieldMatcherValidator
```suggestion
public class FieldMatcherValidator implements ConstraintValidator<FieldMatch, Object> {
```

2023-11-15 14:04 UTC, liliia-ponomarenko approved these changes
Good job! 👍

2023-11-15 14:04 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-table-users.yaml
> +                    nullable: false
add one empty line

2023-11-15 16:13 UTC, merged